services:
  aris-api:
    env_file:
      - .env.staging
    ports:
      - "8001:8000"
    restart: always

  aris-worker:
    env_file:
      - .env.staging
    restart: always

  redis:
    restart: always
