"""create chat_messages

Revision ID: 74d69b7f1883
Revises: 
Create Date: 2026-04-04 14:42:02.652799

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '74d69b7f1883'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
